name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rinchsan/renovate-config-validator@v0.0.11
        with:
          pattern: '*.json' # Regular expression for filename to validate, default to *.json
